async function getJwt(): Promise<string | null> {
  return new Promise((resolve) => {
    chrome.storage.local.get(null, (items) => {
      const key = Object.keys(items).find(
        (k) => k.startsWith("sb-") && k.endsWith("-auth-token")
      );
      if (!key) { resolve(null); return; }
      try {
        const session = JSON.parse(items[key] as string);
        resolve((session as { access_token?: string })?.access_token ?? null);
      } catch {
        resolve(null);
      }
    });
  });
}

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const EDGE_FUNCTION_URL = `${SUPABASE_URL}/functions/v1/suggest`;

async function getCached(key: string): Promise<string | null> {
  return new Promise((resolve) => {
    chrome.storage.session.get(key, (result) => resolve((result[key] as string) ?? null));
  });
}

async function setCached(key: string, value: string): Promise<void> {
  return new Promise((resolve) => {
    chrome.storage.session.set({ [key]: value }, resolve);
  });
}

async function cacheKey(label: string, pathname: string): Promise<string> {
  const raw = `${label}||${pathname}`;
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(raw));
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

chrome.runtime.onMessage.addListener(
  (
    message: {
      type: string;
      label?: string;
      pageTitle?: string;
      jobDescription?: string;
      maxLength?: number | null;
      pathname?: string;
    },
    _sender,
    sendResponse
  ) => {
    if (message.type !== "SUGGEST_FIELD") {
      sendResponse({ ok: false, error: "Unknown message type" });
      return true;
    }

    (async () => {
      const {
        label = "",
        pageTitle = "",
        jobDescription = "",
        maxLength = null,
        pathname = "",
      } = message;

      // Cache keyed on label + pathname so different jobs get fresh suggestions
      const key = await cacheKey(label, pathname);
      const cached = await getCached(key);
      if (cached) {
        try {
          const parsed = JSON.parse(cached) as { reasoning: string; suggestion: string };
          sendResponse({ ok: true, ...parsed, source: "generated by AI" });
        } catch {
          sendResponse({ ok: true, reasoning: "", suggestion: cached, source: "generated by AI" });
        }
        return;
      }

      const jwt = await getJwt();
      if (!jwt) {
        console.error("[FormFill AI] JWT not found in storage");
        sendResponse({ ok: false, error: "Not authenticated" });
        return;
      }
      console.log("[FormFill AI] JWT found, calling Edge Function...");

      try {
        const res = await fetch(EDGE_FUNCTION_URL, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${jwt}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ fieldLabel: label, pageTitle, jobDescription, maxLength }),
        });

        if (!res.ok) {
          const body = await res.text();
          console.error(`[FormFill AI] Edge Function ${res.status}:`, body);
          const error = res.status === 401 ? "auth_expired" : `Edge Function error: ${res.status}`;
          sendResponse({ ok: false, error });
          return;
        }

        const data = (await res.json()) as {
          reasoning: string;
          suggestion: string;
          source: string;
        };

        // Cache the reasoning + suggestion together
        await setCached(key, JSON.stringify({ reasoning: data.reasoning, suggestion: data.suggestion }));
        sendResponse({ ok: true, reasoning: data.reasoning, suggestion: data.suggestion, source: data.source });
      } catch (err) {
        sendResponse({ ok: false, error: String(err) });
      }
    })();

    return true;
  }
);
