export interface PersonalInfo {
  firstName: string;
  lastName: string;
  fullName: string;
  email: string;
  phone: string;
  location: {
    city: string;
    state: string;
    country: string;
    zipCode?: string;
  };
  linkedinUrl?: string;
  githubUrl?: string;
  portfolioUrl?: string;
}

export interface Education {
  id: string;
  institution: string;
  degree: string;
  field: string;
  startDate: string;
  endDate: string;
  gpa?: number;
  gpaScale?: number;
  relevantCourses?: string[];
  honors?: string[];
}

export interface WorkExperience {
  id: string;
  company: string;
  title: string;
  location: string;
  startDate: string;
  endDate: string;
  bullets: string[];
  skills: string[];
  isCurrentRole: boolean;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  bullets: string[];
  url?: string;
  skills: string[];
  startDate?: string;
  endDate?: string;
}

export interface Skill {
  name: string;
  category: "technical" | "soft" | "language" | "tool";
  proficiency?: "beginner" | "intermediate" | "advanced" | "native";
}

export interface ProfileData {
  version: number;
  personal: PersonalInfo;
  education: Education[];
  experience: WorkExperience[];
  projects: Project[];
  skills: Skill[];
  customFields?: Record<string, string>;
}

export interface FieldSuggestion {
  value: string;
  source: "from your profile" | "generated by AI";
}

export interface GetSuggestionMessage {
  type: "GET_SUGGESTION";
  fieldLabel: string;
  pageTitle: string;
  companyName: string;
  maxLength?: number;
}

export interface GetProfileMessage {
  type: "GET_PROFILE";
}

export type ExtensionMessage = GetSuggestionMessage | GetProfileMessage;
